module.exports = {
  ci: {
    collect: {
      numberOfRuns: 3,
      url: [
        'http://localhost:3000',
        'http://localhost:3000/dashboard',
        'http://localhost:3000/dashboard/trading',
        'http://localhost:3000/dashboard/market',
        'http://localhost:3000/login',
      ],
      settings: {
        chromeFlags: '--no-sandbox --disable-dev-shm-usage',
      },
    },
    assert: {
      assertions: {
        'categories:performance': ['error', { minScore: 0.8 }],
        'categories:accessibility': ['error', { minScore: 0.9 }],
        'categories:best-practices': ['error', { minScore: 0.9 }],
        'categories:seo': ['error', { minScore: 0.9 }],
        'categories:pwa': ['error', { minScore: 0.8 }],
      },
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
  
  // Custom audits for crypto trading platform
  extends: 'lighthouse:default',
  
  settings: {
    // Performance optimizations for trading platform
    throttling: {
      rttMs: 40,
      throughputKbps: 10240,
      requestLatencyMs: 0,
      downloadThroughputKbps: 0,
      uploadThroughputKbps: 0,
      cpuSlowdownMultiplier: 1,
    },
    
    // Security-focused audits for crypto platform
    onlyAudits: [
      'first-contentful-paint',
      'largest-contentful-paint',
      'cumulative-layout-shift',
      'total-blocking-time',
      'speed-index',
      'interactive',
      'accessibility-audit',
      'best-practices-audit',
      'seo-audit',
      'pwa-audit',
      'installable-manifest',
      'apple-touch-icon',
      'service-worker',
      'offline-start-url',
      'themed-omnibox',
      'content-width',
      'viewport',
      'document-title',
      'meta-description',
      'http-status-code',
      'link-text',
      'crawlable-anchors',
      'robots-txt',
      'hreflang',
      'canonical',
      'font-display',
      'preload-fonts',
      'unused-css-rules',
      'unused-javascript',
      'modern-image-formats',
      'uses-optimized-images',
      'uses-text-compression',
      'uses-responsive-images',
      'efficient-animated-content',
      'duplicated-javascript',
      'legacy-javascript',
      'preload-lcp-image',
      'total-byte-weight',
      'uses-long-cache-ttl',
      'uses-rel-preconnect',
      'uses-rel-preload',
      'critical-request-chains',
      'user-timings',
      'bootup-time',
      'mainthread-work-breakdown',
      'third-party-summary',
      'third-party-facades',
      'lcp-lazy-loaded',
      'layout-shift-elements',
      'uses-passive-event-listeners',
      'no-document-write',
      'dom-size',
      'no-vulnerable-libraries',
      'js-libraries',
      'notification-on-start',
      'password-inputs-can-be-pasted-into',
      'image-aspect-ratio',
      'image-size-responsive',
      'tap-targets',
      'accesskeys',
      'aria-allowed-attr',
      'aria-command-name',
      'aria-hidden-body',
      'aria-hidden-focus',
      'aria-input-field-name',
      'aria-meter-name',
      'aria-progressbar-name',
      'aria-required-attr',
      'aria-required-children',
      'aria-required-parent',
      'aria-roles',
      'aria-toggle-field-name',
      'aria-tooltip-name',
      'aria-treeitem-name',
      'aria-valid-attr-value',
      'aria-valid-attr',
      'button-name',
      'bypass',
      'color-contrast',
      'definition-list',
      'dlitem',
      'document-title',
      'duplicate-id-active',
      'duplicate-id-aria',
      'form-field-multiple-labels',
      'frame-title',
      'heading-order',
      'html-has-lang',
      'html-lang-valid',
      'image-alt',
      'input-image-alt',
      'label',
      'link-name',
      'list',
      'listitem',
      'meta-refresh',
      'meta-viewport',
      'object-alt',
      'tabindex',
      'td-headers-attr',
      'th-has-data-cells',
      'valid-lang',
      'video-caption',
    ],
    
    // Exclude certain audits that don't apply to crypto platforms
    skipAudits: [
      'canonical',
      'plugins',
    ],
  },
};
