# Netlify configuration for a Next.js application.
# This file tells Netlify how to build and deploy the site.

[build]
  # The command to build the Next.js application.
  command = "NODE_ENV=production npm run build"
  # The directory where the built assets are located.
  publish = ".next"

# This plugin is essential for Next.js on Netlify. It handles server-side rendering,
# API routes, image optimization, and more, automatically.
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false --force"

# Production environment variables
[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_APP_URL = "https://astralcore-quantum.netlify.app"
  JWT_SECRET = "REPLACE_WITH_SECURE_PRODUCTION_SECRET"
  NEXT_PUBLIC_APP_NAME = "AstralCore"
  NEXT_PUBLIC_APP_VERSION = "5.0"
  NEXT_PUBLIC_ENABLE_TRADING = "true"
  NEXT_PUBLIC_ENABLE_DEPOSITS = "true"
  NEXT_PUBLIC_ENABLE_WITHDRAWALS = "true"
  NEXT_PUBLIC_ENABLE_CHAT = "true"

# Deploy preview environment
[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_APP_URL = "https://deploy-preview-BRANCH--astralcore-quantum.netlify.app"

# Branch deploy environment
[context.branch-deploy.environment]
  NODE_ENV = "production"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# API routes handling
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Health check endpoint
[[redirects]]
  from = "/health"
  to = "/api/health"
  status = 200

# SPA routing for client-side pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Performance optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Additional headers for performance
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
