[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PRIVATE_STANDALONE = "true"

# Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[plugins.inputs]
  # Enable Next.js advanced features
  experimental = { optimizeCss = true }

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://static.hotjar.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      media-src 'self' https:;
      connect-src 'self' https: wss: ws:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    '''
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes with CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"

# HTML pages with no cache
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects and rewrites
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/app"
  to = "/dashboard"
  status = 302

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  headers = {X-Frame-Options = "SAMEORIGIN"}

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/:splat"
  status = 200

# API proxy for better performance
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions configuration
[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"
  included_files = ["data/**/*"]

[functions."api-*"]
  node_bundler = "esbuild"
  
# Edge functions
[edge_functions]

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
  autoLaunch = false

# Context-specific build settings
[context.production]
  command = "npm run build"
  
[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.deploy-preview]
  command = "npm run build"
  
[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.branch-deploy]
  command = "npm run build"
  
[context.branch-deploy.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Form handling (if needed)
# [[forms]]
#   name = "contact"
#   action = "/api/contact"
